# POPULATION
POPULATION_SIZE = 300
STANDARD_VARIATION = 1.15
MEAN = 0

# BREEDING
NUMBER_OF_GENERATIONS = 500
PERCENTAGE_SURVIVAL = 0.05
ELITIST_SELECTION = False  # If false, then tournament.
UNIFORM_CROSSOVER = False  # If false, then k-point.
CHANCE_OF_MUTATION = 0.05

# FITNESS
NON_MATCH_PENALTY = -5000

# FILES
FILES = ["genAlgData1.txt", "genAlgData2.txt"]
CREDENTIAL_FILENAME = "credentials.txt"

# OUTPUT
DISPLAY_INTERVALS = 10
VISUALIZATION_ACTIVE = True
TEXT_OUTPUT = True
