import breeding

# POPULATION
POPULATION_SIZE = 200
STANDARD_VARIATION = 1.15
MEAN = 0

# BREEDING
NUMBER_OF_GENERATIONS = 100
PERCENTAGE_SURVIVAL = 0.2
ELITIST_SELECTION = True  # If false, then tournament.
UNIFORM_CROSSOVER = True  # If false, then k-point.
CHANCE_OF_MUTATION = 0.05

# FITNESS
NON_MATCH_PENALTY = -5000

# FILES
FILES = ["genAlgData1.txt", "genAlgData2.txt"]

# OUTPUT
DISPLAY_INTERVALS = 10
